# Hyprland configuration entrypoint
# Split by topic and sourced linearly.
# See: https://wiki.hypr.land/Configuring/Keywords/#sourcing-multi-file

source = ~/.config/hypr/hyprland.d/10-monitors.conf
source = ~/.config/hypr/hyprland.d/20-programs.conf
source = ~/.config/hypr/hyprland.d/30-autostart.conf
source = ~/.config/hypr/hyprland.d/40-environment.conf
source = ~/.config/hypr/hyprland.d/50-permissions.conf
source = ~/.config/hypr/hyprland.d/60-lookandfeel.conf
source = ~/.config/hypr/hyprland.d/70-input.conf
source = ~/.config/hypr/hyprland.d/80-keybindings.conf
source = ~/.config/hypr/hyprland.d/90-window-rules.conf
source = ~/.config/hypr/hyprland.d/95-layer-rules.conf
