################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitorv2 {
    output =
    mode = highrr
    position = auto
    scale = auto
    # bitdepth = 10
    # cm = hdr
    # sdrbrightness = 1.2
    # sdrsaturation = 0.98
}
