##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Window rules are applied to windows when they are created. They can be used to set properties on windows, move them to specific workspaces, make them floating, etc. They are a powerful way to customize the behavior of your windows and workspaces.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
    suppress_event = minimize
}

windowrule {
    # Ignore fullscreen requests from all apps. This is useful if you want to use a custom fullscreen implementation (e.g. a floating window that covers the entire screen) instead of the built-in fullscreen mode.
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    # Move the hyprland-run window to the bottom right corner of the screen and make it floating. This is a small utility window that is used for running commands and displaying notifications, so it's best to keep it out of the way.
    name = move-hyprland-run
    match:class = hyprland-run

    move = 20 monitor_h-120
    float = on
}

windowrule {
    # Move Spotify to the "background" workspace, which is a special workspace that is always behind all other workspaces. This is useful for music players and similar apps that you want to keep open but out of the way.
    name = spotify-move-to-special
    match:class = spotify

    workspace = special:background
}

windowrule {
    # Make all modal popup/dialog windows float
    name = float-all-popups
    match:modal = true

    float = on
}

windowrule {
    # Make all desktop portal dialogs floating (e.g. screen recording permissions, file pickers, etc.)
    name = float-portal-dialogs
    match:class = ^xdg-desktop-portal.*

    float = on
}

windowrule {
    # Make settings window float
    name = float-settings
    match:title = ^.*[Ss]ettings.*$

    float = on
}

windowrule {
    # Mark windows running in xwayland with red border to easily identify them. This is useful for debugging and for identifying apps that may have compatibility issues with Wayland.
    name = mark-xwayland-windows
    match:xwayland = true

    border_color = #ff0000
}