###################
### LAYER RULES ###
###################

# See https://wiki.hypr.land/Configuring/Window-Rules/#layer-rules

layerrule {
    # Enable blur for vicinae
    name = vicinae-blur
    match:namespace = vicinae

    blur = on
    ignore_alpha = 0
}

layerrule {
    # Disable animation for vicinae
    name = vicinae-no-animation
    match:namespace = vicinae

    no_anim = on
}

layerrule {
    # Enable blur for waybar
    name = waybar-blur
    match:namespace = waybar

    blur = on
    ignore_alpha = 0
}
