# Disable splash screen text for a cleaner look
splash = false

# Pre-cache wallpapers for faster loading
preload = ~/images/wallpapers/forest.png

# Wallpaper configurations
wallpaper {
    monitor = , ~/images/wallpapers/forest.png
}